#!/usr/bin/env ruby

require 'rake'
require 'puppetlabs_spec_helper/rake_tasks'

require 'puppet-lint/tasks/puppet-lint'
PuppetLint.configuration.ignore_paths = ["spec/**/*.pp", "vendor/**/*.pp"]

def div_line
  puts "=" * 65
end

def empty_line
  puts "\n"
end

def fail(util)
  div_line
  puts "FAILED: #{util} error(s)!!!"
  puts "You must repair these errors before you can commit."
  div_line
  exit 1
end

def succeed
  puts "PASSED: You are good looking and write stylish Puppet code!"
  div_line
  exit 0
end

def exec_util(util, manifest)
  puts "#{util}: #{manifest}"
  div_line
  puts %x{#{util} #{manifest}}
  empty_line
  fail(__method__) unless $?.success?
end

def puppet_lint(manifest)
  exec_util 'puppet-lint', manifest
end

def puppet_parser(manifest)
  exec_util 'puppet parser validate', manifest
end

def modified_manifests
  %x{git diff --name-only --cached}.split.grep /\A.*\.pp/
end

###################################
# MAIN
###################################

div_line
puts "Running: pre-commit hook..."
empty_line
modified_manifests.each do |file|
  puppet_lint   file
  puppet_parser file
end

succeed
