# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#   Specialized function used to validate raw constructor class resource hashes.
#Expects the value of each key in the resource param to be Hash. If the value is
#not a Hash it's rejected. If the the Hash is exhausted, the resource is
#"validated".
#
#
Puppet::Functions.create_function(:'managedmac::validate_raw_constructor') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    

    e = "validate_raw_constructor(): Wrong number of args: #{args.size} for 1"
    raise(Puppet::ParseError, e) if args.size != 1

    resources = args.first.dup
    resources.reject! { |k,v| v.respond_to? :key }

    e = "one or more invalid resources: #{resources}"
    raise(Puppet::ParseError, e) unless resources.empty?
  
  end
end
