# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#   Expects a pair of version strings. Returns Fixnum: -1 (<), 0 (=) or 1 (>)
#
#
Puppet::Functions.create_function(:'managedmac::version_compare') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    

    if args.size != 2
      e = "version_compare(): Wrong number of args: #{args.size} for 2"
      raise(Puppet::ParseError, e)
    end

    Puppet::Util::Package.versioncmp(*args.collect(&:to_s))
  
  end
end
